---
# Important variables for all the roles can be stored here
# Note that this file will take precidence over role defaults

#
# Example variable definition
test_var: "Hello World"

#
# Note that ansible-vault can be used to encrypt secret values in variable definitions.
# This projects ansible.cfg looks for a vault key in your home directory for convenience. 
#
## To encrypt a variable into this file (not the whole file) from project root type:
# ansible-vault encrypt_string 'text-to-encrpyt' --name 'test_sudo_pass' >>./group_vars/all.yml
#
## To show the variable value (cant use view since not whole file) from project root type:
# ansible localhost -m ansible.builtin.debug -a var="test_sudo_pass" -e "@./group_vars/all.yml"
#
# The project root is where the ansible.cfg is which calls the vault key in the home directory
# If that key was not configured or you run from elsewhere youll be prompted for the key

#
# Example vault encrypted variable definition
test_sudo_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          12345678901234567890123456789012345678901234567890123456789012345678901234567890
          12345678901234567890123456789012345678901234567890123456789012345678901234567890
          12345678901234567890123456789012345678901234567890123456789012345678901234567890
          12345678901234567890123456789012345678901234567890123456789012345678901234567890
          1234
