galaxy_info:
  author: Richard Gowen
  description: This role will get a vm ready as a target for the ceres_awx project.

  license: MIT

  min_ansible_version: 2.9

  galaxy_tags: []

dependencies:
  - community.general
  - ansible.posix
