---
- name: AZ Setup Test Playbook
  hosts: localhost
  become: true

  vars:
    launch_role_azsetup: True

  tasks:
  # 
  # Call role ceres_localenv to resize root partition on vm for DEV AWX
  - name: Import role ceres_azsetup
    ansible.builtin.import_role:
      name: ceres_azsetup
    when: launch_role_azsetup
