---
- name: AZ Setup Playbook - Prepare Azure environment and a VM in Azure
  hosts: localhost
  become: true

  tasks:
  # 
  # Call role ceres_azsetup to create an AWX target machine in Azure
  - name: Import role ceres_azsetup
    ansible.builtin.import_role:
      name: ceres_azsetup
