---
- name: Dev Test Playbook
  hosts: ceresdev
  become: true

  tasks:
  # 
  # Call role ceres_localenv to resize root partition on vm for DEV AWX
  - name: Import role ceres_localenv
    ansible.builtin.import_role:
      name: ceres_localenv
    vars:
      ceres_localenv_resize_disk: True
      ceres_localenv_resize_dev: "/dev/sda"
      ceres_localenv_pkgs_qol_install: True

  #
  # Call role ceres_k3s to install k3s varient of Kubernetes on vm for DEV AWX
  - name: Import role ceres_k3s
    ansible.builtin.import_role:
      name: ceres_k3s
    vars:
      ceres_k3s_installer_version: "v1.25.6+k3s1"
      ceres_k3s_installer_channel: "stable"
      ceres_k3s_exec_role: "server"
      ceres_k3s_kube_dashboard_install: True
      ceres_k3s_nginx_ingress_install: True

  #
  # Call role ceres_awx to install awx on vm for DEV AWX
  - name: Import role ceres_awx
    ansible.builtin.import_role:
      name: ceres_awx
    vars:
      #ceres_awx_ansible_token: "{{ ceres_k3s_ansible_token }}"
      ceres_awx_node_ip_address: "{{ omit if ceres_k3s_node_ip_address is not defined else ceres_k3s_node_ip_address }}"
      ceres_awx_node_fqdn: "{{ omit if ceres_k3s_node_fqdn is not defined else ceres_k3s_node_fqdn }}"

