---
- name: Azure Playbook - Install Ansible AWX onto a VM in Azure that our azsetup job created
  hosts: ceresanyvm
  become: true

  # By default three main roles are run
  # These can be disabled for testing by setting these launch values to False
  vars:
    launch_role_localenv: True
    launch_role_k3s: True
    launch_role_awx: True

  tasks:
  # 
  # Call role ceres_localenv to resize root partition on target machine for AWX
  - name: Import role ceres_localenv
    ansible.builtin.import_role:
      name: ceres_localenv
    vars:
      ceres_localenv_pkgs_qol_install: True
      ceres_localenv_pkgs_build_install: False
      ceres_localenv_pkgs_ansible_install: False
      ceres_localenv_custom_color_prompt: True
      ceres_localenv_custom_color_prompt_git_support: False
    when: launch_role_localenv

  #
  # Call role ceres_k3s to install k3s varient of Kubernetes on target machine for AWX
  - name: Import role ceres_k3s
    ansible.builtin.import_role:
      name: ceres_k3s
    vars:
      # k3s defaults - uncomment to change as needed
      #ceres_k3s_installer_version: "v1.25.6+k3s1"
      #ceres_k3s_installer_channel: "stable"
      #ceres_k3s_exec_role: "server"
      #
      # k3s installation is required for AWX set to false to uninstall
      ceres_k3s_installer_install: True
      #
      # Reinstall k3s by setting this to True
      # Good for changing versions as it does uninstall then install
      ceres_k3s_installer_reinstall: False
      #
      # This ingress is required for awx
      ceres_k3s_nginx_ingress_install: True
      #
      # Dashboard is not required but can be nice, change below to True to install
      ceres_k3s_kube_dashboard_install: False
      ceres_k3s_dashboard_ingress_install: False
    when: launch_role_k3s

  #
  # Call role ceres_awx to install awx on target machine
  - name: Import role ceres_awx
    ansible.builtin.import_role:
      name: ceres_awx
    vars:
      ceres_awx_ansible_token: "{{ omit if ceres_k3s_ansible_token is not defined else ceres_k3s_ansible_token }}"
      #
      # awx install and ingress are required, setting to false will uninstall
      # which can be helpful if troubleshooting a bad install
      ceres_awx_oper_install: True
      ceres_awx_ingress_install: True
      #
      # This is the version of awx-operator to install via helm
      # NOTE This is not the awx version but operator which determines it
      # Example awx-operator version 2.5.2 will depoly awx version 23.0.0
      # See this link for release information https://github.com/ansible/awx-operator/tags
      # By default it pulls latest version to change it uncomment below
      #ceres_awx_oper_helm_deploy_chart_version: "2.5.1"
    when: launch_role_awx

  # Save connection details to local files
  - name: Save Dashboard Ingress Connection Info
    ansible.builtin.copy:
      content: "{{ ceres_k3s_dashboard_ingress_connect }}\n"
      dest: "CONNECT_{{ inventory_hostname }}_dashboard.key"
    delegate_to: localhost
    when:
      - ceres_k3s_dashboard_ingress_connect is defined
      - ceres_k3s_dashboard_ingress_connect != None
  - name: Save AWX Ingress Connection Info
    ansible.builtin.copy:
      content: "{{ ceres_awx_ingress_connect }}\n"
      dest: "CONNECT_{{ inventory_hostname }}_awx.key"
    delegate_to: localhost
    when:
      - ceres_awx_ingress_connect is defined
      - ceres_awx_ingress_connect != None

  # Print final status messages
  - name: Print Dashboard Ingress Connection Info
    ansible.builtin.debug:
      msg: "{{ ceres_k3s_dashboard_ingress_connect.split('\n') }}"
      verbosity: 0
    when: 
      - ceres_k3s_dashboard_ingress_connect is defined
      - ceres_k3s_dashboard_ingress_connect != None
  - name: Print AWX Ingress Connection Info
    ansible.builtin.debug:
      msg: "{{ ceres_awx_ingress_connect.split('\n') }}"
      verbosity: 0
    when: 
      - ceres_awx_ingress_connect is defined
      - ceres_awx_ingress_connect != None

