galaxy_info:
  author: Richard Gowen
  description: This role will install awx

  license: MIT

  min_ansible_version: 2.9

  galaxy_tags: []

dependencies: []
  # Uses the following collections
  # ansible.posix
  # community.general
  # kubernetes.core
  # 
  # This role depends on the role ceres_k3s
