---
# defaults main.yml file

## k3s installer defaults
ceres_k3s_installer_url: "https://get.k3s.io"
ceres_k3s_installer_directory: /opt/k3s
ceres_k3s_installer_version: "v1.32.3+k3s1"
#ceres_k3s_installer_version: "v1.25.6+k3s1"
ceres_k3s_installer_channel: "stable"
ceres_k3s_installer_install: True
ceres_k3s_installer_reinstall: False

## helm installer (set to empty to disable installation)
ceres_k3s_helm_installer_url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"

## k3s environment
ceres_k3s_bin_directory: /usr/local/bin
ceres_k3s_storage_provider: local
ceres_k3s_default_storage_path: /srv/data
ceres_k3s_config_file: /etc/rancher/k3s/config.yaml
ceres_k3s_ansible_token_file: /etc/rancher/k3s/ansible-node-token
ceres_k3s_ansible_token:
ceres_k3s_kubeconfig_file: /etc/rancher/k3s/k3s.yaml
ceres_k3s_kubeconfig_file_root: /root/.kube/config
ceres_k3s_kube_app_defs_path: /root/kube_app_defs
ceres_k3s_service_name: "k3s.service"
ceres_k3s_cluster_cidr: "192.168.1.0/24"
ceres_k3s_service_cidr: "192.168.2.0/24"
ceres_k3s_exec_role: "server" # [server|agent] only server supported at this time

## k3s node references
#    Node IP will be populated from ansible_default_ipv4 unless provided
ceres_k3s_node_ip_address:

## Kube Dashboard
ceres_k3s_kube_dashboard_install: False # Set to true to install and false to prevent or remove install
ceres_k3s_kube_dashboard_reinstall: False
ceres_k3s_kube_dashboard_token_file: /etc/rancher/k3s/dashboard-token
ceres_k3s_kube_dashboard_token:
ceres_k3s_kube_dashboard_servicename: kubernetes-dashboard-kong-proxy
ceres_k3s_kube_dashboard_deployment_name: kubernetes-dashboard-web
ceres_k3s_kube_dashboard_helm_repo_url: "https://kubernetes.github.io/dashboard/"
ceres_k3s_kube_dashboard_helm_repo_name: kubernetes-dashboard
ceres_k3s_kube_dashboard_helm_deploy_name: kubernetes-dashboard
ceres_k3s_kube_dashboard_helm_deploy_chart_ref: kubernetes-dashboard/kubernetes-dashboard
ceres_k3s_kube_dashboard_helm_deploy_namespace: kubernetes-dashboard
ceres_k3s_kube_dashboard_helm_deploy_chart_version:
#ceres_k3s_kube_dashboard_version: "v2.7.0"

## NGINX INGRESS CONTROLLER
ceres_k3s_nginx_ingress_install: True # Set to false to prevent install or remove install
ceres_k3s_nginx_ingress_reinstall: False

# Dashboard Ingress
ceres_k3s_dashboard_ingress_install: True
# Connection Details
ceres_k3s_dashboard_ingress_connect:
# This fqdn value must be set in inventory or playbook since fqdn will be used by ingress
ceres_awx_ingress_fqdn:
