---
# defaults main.yml file

## k3s installer defaults
ceres_k3s_installer_url: "https://get.k3s.io"
ceres_k3s_installer_directory: /opt/k3s
ceres_k3s_installer_version: ""
ceres_k3s_installer_channel: "stable"
ceres_k3s_installer_reinstall: False

## k3s environment
ceres_k3s_bin_directory: /usr/local/bin
ceres_k3s_storage_provider: local
ceres_k3s_default_storage_path: /srv/data
ceres_k3s_config_file: /etc/rancher/k3s/config.yaml
ceres_k3s_kubeconfig_file: /etc/rancher/k3s/k3s.yaml
ceres_k3s_service_name: "k3s.service"
ceres_k3s_cluster_cidr: "10.42.0.0/16"
ceres_k3s_service_cidr: "10.43.0.0/16"
ceres_k3s_exec_role: "server" # [server|agent] only server supported at this time

