---
# tasks main.yml file

#$ helm repo add awx-operator https://ansible.github.io/awx-operator/
#"awx-operator" has been added to your repositories
#
#$ helm repo update
#Hang tight while we grab the latest from your chart repositories...
#...Successfully got an update from the "awx-operator" chart repository
#Update Complete. ⎈Happy Helming!⎈
#
#$ helm search repo awx-operator
#NAME                            CHART VERSION   APP VERSION     DESCRIPTION
#awx-operator/awx-operator       0.17.1          0.17.1          A Helm chart for the AWX Operator
#
#$ helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator
#NAME: my-awx-operator
#LAST DEPLOYED: Thu Feb 17 22:09:05 2022
#NAMESPACE: default
#STATUS: deployed
#REVISION: 1
#TEST SUITE: None
#NOTES:
#Helm Chart 0.17.1

## OS Check ##
- name: OS Check
  ansible.builtin.fail:
    msg: The role currently only supports CentOS and RHEL distributions.
  when: ansible_distribution not in ['CentOS', 'Red Hat Enterprise Linux']

## Check for k3s token (needed to access k3s api)
- name: Look for k3s token if not provided
  block:
    - name: Stat k3s token file
      ansible.builtin.stat: path="{{ ceres_awx_ansible_token_file }}"
      register: reg_k3_token_file
    - name: Fail if no k3s token found
      ansible.builtin.fail:
        msg: The role requires k3s installed and token created to access kubernetes api.
      when: not reg_k3_token_file.stat.exists
    # Get token contents if token file exists on host
    - name: lookup k3s ansible token
      ansible.builtin.slurp:
        src: "{{ ceres_awx_ansible_token_file }}"
      register: reg_slurp_k3s_ansible_token
      when: reg_k3_token_file.stat.exists
    # Decode token contents for ansible use
    - name: set fact for k3s ansible token
      ansible.builtin.set_fact:
        ceres_awx_ansible_token: "{{ reg_slurp_k3s_ansible_token['content'] | b64decode }}"
      when: reg_k3_token_file.stat.exists and reg_slurp_k3s_ansible_token.content is defined
  when: ceres_awx_ansible_token is not defined or ceres_awx_ansible_token == None or ceres_awx_ansible_token | length == 0
#
# Dump the output of previous task if needed for troubleshooting
- name: "Debug task output"
  ansible.builtin.debug:
    var: ceres_awx_ansible_token
    verbosity: 1

## Add helm repo for awx operator
#
- name: Add awx operator helm repository
  kubernetes.core.helm_repository:
    name: "{{ ceres_awx_oper_helm_repo_name }}"
    repo_url: "{{ ceres_awx_oper_helm_repo_url }}"

#helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator
- name: Use helm to deploy awx operator inside awx namespace (create namespace if needed)
  kubernetes.core.helm:
    api_key: "{{ ceres_awx_ansible_token }}"
    name: "{{ ceres_awx_oper_helm_deploy_name }}"
    chart_ref: "{{ ceres_awx_oper_helm_deploy_chart_ref }}"
    release_state: present
    release_namespace: "{{ ceres_awx_oper_helm_deploy_namespace }}"
    create_namespace: True
    wait: True
    update_repo_cache: True

