---
- hosts: localhost
  gather_facts: false
  vars_files:
    - build-vars.yml
  tasks:
    - name: Copy build files to build directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ ee_dir }}/"
      with_fileglob: "config-ee*"

    - name: Remove EE context from previous builds
      ansible.builtin.file:
        path: "{{ ee_dir }}/context"
        state: absent

    - name: Create new EE context
      ansible.builtin.shell:
        chdir: "{{ ee_dir }}"
        cmd: "ansible-builder create --file config-ee.yml"

    - name: EE Build Block
      block:
        - name: Build the EE - This can take a LONG time - set a 20min async timeout
          ansible.builtin.shell:
            chdir: "{{ ee_dir }}"
            cmd: "podman build -f context/Containerfile --tag={{ ee_name }}:{{ ee_version }} context"
          async: 1200
          poll: 15
          register: reg_buildee_result
        - name: Tag the new EE build with latest
          ansible.builtin.shell:
            chdir: "{{ ee_dir }}"
            cmd: "podman tag {{ ee_name }}:{{ ee_version }} {{ ee_name }}:latest"
          register: reg_tagee_result
      always:
        # Make sure we prune all the temp images even in a failure
        - name: Prune unused images
          ansible.builtin.shell:
            cmd: "podman image prune -f"
        # Show build results
        - name: "Show build results"
          ansible.builtin.debug:
            var: reg_buildee_result
            # Change this to 1 to suppress output without -v
            verbosity: 0
        # Debug tag latest results
        - name: "Debug tag latest results"
          ansible.builtin.debug:
            var: reg_tagee_result
            verbosity: 1
    - name: EE Build Block
      block:
        - name: Publish the ee image to a container registry
          ansible.builtin.shell:
            cmd: "podman push localhost/{{ ee_name }} docker://{{ ee_publush_url }}/{{ ee_name }}:{{ ee_version }}"
          register: reg_publish_results
        - name: Publish the ee image latest tag to a container registry
          ansible.builtin.shell:
            cmd: "podman push localhost/{{ ee_name }} docker://{{ ee_publush_url }}/{{ ee_name }}:latest"
          register: reg_publish_latest_results
      rescue:
        # Debug Failure Results
        - name: "Debug failure results"
          ansible.builtin.debug:
            msg:
            - "{{ omit if reg_publish_results is not defined else reg_publish_results }}"
            - "{{ omit if reg_publish_latest_results is not defined else reg_publish_latest_results }}"
            verbosity: 0
        # Print user friendly failure message
        - name: Publish Failure Message
          ansible.builtin.debug:
            msg:
              - "PUBLISH FAILED"
              - "This is usually because of lack of permissions to the container registry"
              - ""
              - "You may need to log into your registry.  For docker hub that would look like this:"
              - "podman login -u <docker-username> -p <docker-passwd-or-token> docker.io/<docker-username>"
              - ""
              - "After providing credentials attempt to publish again using these commands:"
              - "podman push localhost/{{ ee_name }} docker://{{ ee_publush_url }}/{{ ee_name }}:{{ ee_version }}"
              - "podman push localhost/{{ ee_name }} docker://{{ ee_publush_url }}/{{ ee_name }}:latest"
            verbosity: 0
      when: ee_publish
