---
- hosts: localhost
  gather_facts: false
  vars_files:
    - build-vars.yml
  tasks:
    - name: Copy build files to build directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ ee_dir }}/"
      with_fileglob: "config-ee*"

    - name: Remove EE context from previous builds
      ansible.builtin.file:
        path: "{{ ee_dir }}/context"
        state: absent

    - name: Create new EE context
      ansible.builtin.shell:
        chdir: "{{ ee_dir }}"
        cmd: "ansible-builder create --file config-ee.yml"

    - name: Build the EE - This can take a LONG time - set a 15min async timeout
      ansible.builtin.shell:
        chdir: "{{ ee_dir }}"
        cmd: "podman build -f context/Containerfile --tag={{ ee_name }}:{{ ee_version }} context"
      async: 900
      poll: 15

    - name: Prune unused images
      ansible.builtin.shell:
        cmd: "podman image prune -f"

    - name: Publish the ee image to a container registry
      ansible.builtin.shell:
        cmd: "podman push localhost/{{ ee_name }}:{{ ee_version }} docker://{{ ee_publish_fqdn }}/{{ ee_name }}:{{ ee_version }}"
      when: ee_publish
