---
# galaxy collection requirements
collections:
  - name: amazon.aws
    version: 5.2.0
  - name: ansible.posix
    version: 1.5.1
  - name: ansible.utils
    version: 2.8.0
  - name: ansible.windows
    version: 1.13.0
  - name: awx.awx
    version: 21.12.0
  - name: azure.azcollection
    version: 1.14.0
  - name: community.general
    version: 6.3.0
  - name: community.windows
    version: 1.12.0
  - name: containers.podman
    version: 1.10.1
  - name: google.cloud
    version: 1.1.2
  - name: kubernetes.core
    version: 2.4.0
  - name: openstack.cloud
    version: 2.0.0
  - name: redhatinsights.insights
    version: 1.0.7
  - name: theforeman.foreman
    version: 3.9.0
