---
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'
  EE_BUILDER_IMAGE: 'quay.io/ansible/ansible-builder:latest'

dependencies:
  galaxy: config-ee-galaxy-requirements.yml
  python: config-ee-python-requirements.txt

# additional_build_steps:
#   prepend: |
#     ADD localfile /some/path/inside/ee/file
#     RUN whoami
#   append:
#     - RUN echo This is a post-install command!