---
# tasks main.yml file

# PREREQUISITES

- name: Read disk {{ ceres_prereq_resize_dev }} information
  community.general.parted: device={{ ceres_prereq_resize_dev }} unit=MiB
  register: reg_resize_info

- name: Debug disk {{ ceres_prereq_resize_dev }} information
  ansible.builtin.debug:
    var: reg_resize_info
    verbosity: 0

- name: Extend partition to fill all available space
  ansible.builtin.command: "echo -e 'resizepart\n{{ reg_resize_info.partitions | length }}\nYes\n100%\nprint free\nquit' | parted {{ ceres_prereq_resize_dev }} ---pretend-input-tty"
  when: "{{ ceres_prereq_resize_root }}"

# this might work on non-mounted partitions but fails on root partition
# saving this snippet for later
#- name: Extend existing partition on /dev/sda to fill all available space
#  community.general.parted:
#    device: /dev/sda
#    number: "{{ reg_resize_info.partitions | length }}"
#    part_end: "100%"
#    resize: true
#    state: present

- name: Extend ext4 filesystem to fill all available space
  ansible.builtin.command: "resize2fs {{ ceres_prereq_resize_dev }}{{ reg_resize_info.partitions | length }}"
  when: "{{ ceres_prereq_resize_root }}"
