---
# tasks main.yml file

#########################
#
# PREREQUISITES
#
#########################

## OS Check ##
- name: OS Check
  ansible.builtin.fail:
    msg: The role currently only supports CentOS and RHEL distributions.
  when: ansible_distribution not in ['CentOS', 'Red Hat Enterprise Linux']

## DISABLE SELINUX & FIREWALLD
#
# selinux
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
#
# firewalld
- name: Stop and Disable FirewallD
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: False

## IP FORWARDING
# 
# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: True
    state: present
    reload: True

## MODPROBE BR_NETFILTER MODULE
#
# Add Modprobe br_netfilter module
- name: Add br_netfilter to /etc/modules-load.d/
  ansible.builtin.template:
    src: "br_netfilter.conf.j2"
    dest: "/etc/modules-load.d/br_netfilter.conf"
    owner: root
    group: root
    mode: 0600
#
# Load Modprobe br_netfilter module
- name: Load br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

## SUDO SECURE_PATH
#
# Add /usr/local/bin to sudo secure_path
- name: Add /usr/local/bin to sudo secure_path
  ansible.builtin.lineinfile:
    line: Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
    regexp: Defaults(\s)*secure_path(\s)*=
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: visudo -cf %s

## Setup Dirs
#
# Make sure the directories we need exist
- name: create required directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
  loop:
    - path: "{{ ceres_k3s_installer_directory }}"
      mode: "0700"
      owner: root
      group: root
    - path: "{{ ceres_k3s_bin_directory }}"
      mode: "0755"
    - path: "{{ ceres_k3s_default_storage_path }}"
      mode: "0755"
    - path: "{{ ceres_k3s_config_file | dirname }}"
      mode: "0750"
    - path: "{{ ceres_k3s_ansible_token_file | dirname }}"
      mode: "0750"

#########################
#
# DOWNLOAD AND INSTALL
#
#########################

## Check if k3s already installed
- name: Stat k3s binary
  ansible.builtin.stat: path="{{ ceres_k3s_bin_directory }}/k3s"
  register: reg_k3binary

## Download installer if needed
- name: Download k3s installer
  ansible.builtin.get_url:
    url: "{{ ceres_k3s_installer_url }}"
    dest: "{{ ceres_k3s_installer_directory }}/k3s-install.sh"
    mode: "0700"
  when: not reg_k3binary.stat.exists or ceres_k3s_installer_reinstall

#- name: create k3s server config file
#  template:
#    src: "k3s-server-config.yaml.j2"
#    dest: "{{ ceres_k3s_config_file }}"
#    owner: root
#    group: root
#    mode: "0440"

## INSTALL BLOCK
- name: Install Block
  block:
    - name: Set facts for installer environment
      set_fact:
        ceres_k3s_install_env:
          INSTALL_K3S_VERSION: "{{ ceres_k3s_installer_version }}"
          INSTALL_K3S_CHANNEL: "{{ ceres_k3s_installer_channel }}"
          INSTALL_K3S_BIN_DIR: "{{ ceres_k3s_bin_directory }}"
          INSTALL_K3S_EXEC: "{{ ceres_k3s_exec_role }}"
          INSTALL_K3S_SKIP_START: "true"
    # Install k3s using defined environment
    - name: Execute k3s installer
      ansible.builtin.command:
        cmd: "{{ ceres_k3s_installer_directory }}/k3s-install.sh"
        creates: "{{ ceres_k3s_bin_directory }}/k3s"
      environment: "{{ ceres_k3s_install_env }}"
      register: reg_k3s_install
  # Always create the logs even if install fails
  always:
    - name: Create k3s install logs
      ansible.builtin.copy:
        dest: "{{ ceres_k3s_installer_directory }}/k3s-install.{{ item.type }}.log"
        content: |
          # k3s install log ({{ item.type }})
          # start: {{ reg_k3s_install.start }}
          # environment:
          {% for k, v in ceres_k3s_install_env.items() %}
          {{ k }}={{ v }}
          {% endfor %}
          # log:
          {{ reg_k3s_install[item.type] }}
          # end: {{ reg_k3s_install.end }}
        mode: "0440"
      loop:
        - type: stdout
        - type: stderr
      when: reg_k3s_install.changed | bool
  # Install block conditionals
  when: not reg_k3binary.stat.exists or ceres_k3s_installer_reinstall


- name: create k3s server config file
  template:
    src: "{{ __k3s_config_template }}"
    dest: "{{ __k3s_config_file }}"
    owner: root
    group: root
    mode: "0440"
  tags: config







#### from titan

# Start the k3s service
#- name: Enable and check K3s service
#  systemd:
#    name: k3s
#    daemon_reload: yes
#    state: restarted
#    enabled: yes

#- name: Wait for node-token
#  wait_for:
#    path: "{{ k3s_server_location }}/server/node-token"

# Create User Config Directory
#- name: Create directory .kube
#  file:
#    path: ~{{ ansible_user }}/.kube
#    state: directory
#    owner: "{{ ansible_user }}"
#    mode: "u=rwx,g=rx,o="

# Copy config file to user home directory
#- name: Copy config file to user home directory
#  copy:
#    src: /etc/rancher/k3s/k3s.yaml
#    dest: ~{{ ansible_user }}/.kube/config
#    remote_src: yes
#    owner: "{{ ansible_user }}"
#    mode: "u=rw,g=r,o=r"

# Symlink for kubectl
#- name: Create kubectl symlink
#  file:
#    src: /usr/local/bin/k3s
#    dest: /usr/local/bin/kubectl
#    state: link

# Symlinks for crictl
#- name: Create crictl symlink
#  file:
#    src: /usr/local/bin/k3s
#    dest: /usr/local/bin/crictl
#    state: link


