---
# tasks main.yml file

#########################
#
# PREREQUISITES
#
#########################

## OS Check ##
- name: OS Check
  ansible.builtin.fail:
    msg: The role currently only supports CentOS and RHEL distributions.
  when: ansible_distribution not in ['CentOS', 'Red Hat Enterprise Linux']

## DISABLE SELINUX & FIREWALLD
#
# selinux
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
#
# firewalld
- name: Stop and Disable FirewallD
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: False

## IP FORWARDING
# 
# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: True
    state: present
    reload: True

## MODPROBE BR_NETFILTER MODULE
#
# Add Modprobe br_netfilter module
- name: Add br_netfilter to /etc/modules-load.d/
  ansible.builtin.template:
    src: "br_netfilter.conf.j2"
    dest: "/etc/modules-load.d/br_netfilter.conf"
    owner: root
    group: root
    mode: 0600
#
# Load Modprobe br_netfilter module
- name: Load br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

## SUDO SECURE_PATH
#
# Add /usr/local/bin to sudo secure_path
- name: Add /usr/local/bin to sudo secure_path
  ansible.builtin.lineinfile:
    line: Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
    regexp: Defaults(\s)*secure_path(\s)*=
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: visudo -cf %s

## Setup Dirs
#
# Make sure the directories we need exist
- name: create required directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
  loop:
    - path: "{{ ceres_k3s_installer_directory }}"
      mode: "0700"
      owner: root
      group: root
    - path: "{{ ceres_k3s_bin_directory }}"
      mode: "0755"
    - path: "{{ ceres_k3s_default_storage_path }}"
      mode: "0755"
    - path: "{{ ceres_k3s_kube_app_defs_path }}"
      mode: "0750"
    - path: "{{ ceres_k3s_config_file | dirname }}"
      mode: "0750"
    - path: "{{ ceres_k3s_kubeconfig_file_root | dirname }}"
      mode: "0700"
      owner: root
      group: root

#########################
#
# DOWNLOAD AND INSTALL
#
#########################

## Check if k3s already installed
- name: Stat k3s binary
  ansible.builtin.stat: path="{{ ceres_k3s_bin_directory }}/k3s"
  register: reg_k3binary

## Download installer if needed
- name: Download k3s installer
  ansible.builtin.get_url:
    url: "{{ ceres_k3s_installer_url }}"
    dest: "{{ ceres_k3s_installer_directory }}/k3s-install.sh"
    mode: "0700"
  when: not reg_k3binary.stat.exists or ceres_k3s_installer_reinstall

## INSTALL BLOCK
- name: Install Block
  block:
    # Server Config File
    - name: create k3s server config file
      ansible.builtin.template:
        src: "k3s-server-config.yaml.j2"
        dest: "{{ ceres_k3s_config_file }}"
        owner: root
        group: root
        mode: "0440"
      when: ceres_k3s_exec_role == "server"
    # Define installer environment
    - name: Set facts for installer environment
      ansible.builtin.set_fact:
        ceres_k3s_install_env:
          INSTALL_K3S_VERSION: "{{ ceres_k3s_installer_version }}"
          INSTALL_K3S_CHANNEL: "{{ ceres_k3s_installer_channel }}"
          INSTALL_K3S_BIN_DIR: "{{ ceres_k3s_bin_directory }}"
          INSTALL_K3S_EXEC: "{{ ceres_k3s_exec_role }}"
          INSTALL_K3S_SKIP_START: "true"
    # Install k3s using defined environment
    - name: Execute k3s installer
      ansible.builtin.command:
        cmd: "{{ ceres_k3s_installer_directory }}/k3s-install.sh"
        creates: "{{ ceres_k3s_bin_directory }}/k3s"
      environment: "{{ ceres_k3s_install_env }}"
      register: reg_k3s_install
  # Always create the logs even if install fails
  always:
    - name: Create k3s install logs
      ansible.builtin.copy:
        dest: "{{ ceres_k3s_installer_directory }}/k3s-install.{{ item.type }}.log"
        content: |
          # k3s install log ({{ item.type }})
          # start: {{ reg_k3s_install.start }}
          # environment:
          {% for k, v in ceres_k3s_install_env.items() %}
          {{ k }}={{ v }}
          {% endfor %}
          # log:
          {{ reg_k3s_install[item.type] }}
          # end: {{ reg_k3s_install.end }}
        mode: "0440"
      loop:
        - type: stdout
        - type: stderr
      when: reg_k3s_install.changed | bool
  # Install block conditionals
  when: not reg_k3binary.stat.exists or ceres_k3s_installer_reinstall

- name: Start and enable the k3s server service
  ansible.builtin.service:
    name: "{{ ceres_k3s_service_name }}"
    state: started
    enabled: true

- name: Wait for kubeconfig file
  ansible.builtin.wait_for:
    path: "{{ ceres_k3s_kubeconfig_file }}"
    state: present

- name: create root's kubeconfig
  ansible.builtin.copy:
    src: "{{ ceres_k3s_kubeconfig_file }}"
    remote_src: true
    dest: "{{ ceres_k3s_kubeconfig_file_root }}"
    owner: root
    group: root
    mode: "0600"

## Kube Dashboard
#
# Check if dashboard is already deployed
#- name: Query k3s to see if kubernetes-dashboard deployment exists
#  ansible.builtin.set_fact:
#    ceres_k3s_kube_dashboard_deployment_q: "{{ query('kubernetes.core.k8s', kind='Deployment', namespace='kubernetes-dashboard', resource_name='kubernetes-dashboard') }}"
# Dump the output of query task if needed for troubleshooting
#- name: "Debug query tasks output"
#  ansible.builtin.debug:
#    msg:
#    - "{{ omit if ceres_k3s_kube_dashboard_deployment_q is not defined else ceres_k3s_kube_dashboard_deployment_q }}"
#    verbosity: 0
# Deployment Block
- name: Kube Dashboard Block
  block:
    # Define Kube Dashboard installer environment
    - name: Get Kube Dashboard Version
      ansible.builtin.shell:
        cmd: "curl -w '%{url_effective}' -I -L -s -S https://github.com/kubernetes/dashboard/releases/latest -o /dev/null | sed -e 's|.*/||'"
      register: reg_kube_dashboard_version
    - name: Set facts for Kube Dashboard installer environment
      ansible.builtin.set_fact:
        ceres_k3s_kube_dashboard_install_env:
          VERSION_KUBE_DASHBOARD: "{{ reg_kube_dashboard_version.stdout }}"
    # Install Kube Dashboard using defined environment
    - name: Install Kube Dashboard
      ansible.builtin.command:
        cmd: "k3s kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/${VERSION_KUBE_DASHBOARD}/aio/deploy/recommended.yaml"
        #cmd: "k3s kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/${VERSION_KUBE_DASHBOARD}/aio/deploy/alternative.yaml"
      environment: "{{ ceres_k3s_kube_dashboard_install_env }}"
      register: reg_kube_dashboard_install
    # Dashboard Admin User Definitions
    - name: Dashboard admin user definition file
      ansible.builtin.template:
        src: "dashboard.admin-user.yml.j2"
        dest: "{{ ceres_k3s_kube_app_defs_path }}/dashboard.admin-user.yml"
        owner: root
        group: root
        mode: "0440"
    - name: Dashboard admin rbac definition file
      ansible.builtin.template:
        src: "dashboard.admin-user-role.yml.j2"
        dest: "{{ ceres_k3s_kube_app_defs_path }}/dashboard.admin-user-role.yml"
        owner: root
        group: root
        mode: "0440"
    # Deploy admin user config
    - name: Deploy admin user config in Kube Dashboard
      ansible.builtin.command:
        cmd: "k3s kubectl create -f {{ ceres_k3s_kube_app_defs_path }}/dashboard.admin-user.yml -f {{ ceres_k3s_kube_app_defs_path }}/dashboard.admin-user-role.yml"
      register: reg_kube_dashboard_deploy
    # Get admin token
    - name: Create the admin token for Kube Dashboard
      ansible.builtin.command:
        cmd: "k3s kubectl -n kubernetes-dashboard create token admin-user"
      register: reg_kube_dashboard_admin_token
  always:
    #
    # Dump the output of block tasks if needed for troubleshooting
    - name: "Debug block tasks output"
      ansible.builtin.debug:
        msg:
        - "{{ omit if reg_kube_dashboard_version is not defined else reg_kube_dashboard_version }}"
        - "{{ omit if reg_kube_dashboard_install is not defined else reg_kube_dashboard_install }}"
        - "{{ omit if reg_kube_dashboard_deploy is not defined else reg_kube_dashboard_deploy}}"
        - "{{ omit if reg_kube_dashboard_admin_token is not defined else reg_kube_dashboard_admin_token}}"
        verbosity: 0
#
# Check if dashboard is already deployed
#- name: Query k3s to see if kubernetes-dashboard deployment exists
#  ansible.builtin.set_fact:
#    ceres_k3s_kube_dashboard_deployment_r: "{{ query('kubernetes.core.k8s', kind='Deployment', namespace='kubernetes-dashboard', resource_name='kubernetes-dashboard') }}"
# Dump the output of query task if needed for troubleshooting
#- name: "Debug query tasks output"
#  ansible.builtin.debug:
#    msg:
#    - "{{ omit if ceres_k3s_kube_dashboard_deployment_r is not defined else ceres_k3s_kube_dashboard_deployment_r }}"
#    verbosity: 0



