---
# defaults main.yml file

##
## Azure Required Values (provided via a vault file somewhere like group_vars/all.yml)
##
ceres_azsetup_az_tenant_id: "{{ az_tenant_id }}"
ceres_azsetup_az_subscription_id: "{{ az_subscription_id }}"
ceres_azsetup_az_resource_group_name: "{{ az_resource_group_name }}"
ceres_azsetup_az_spn_client_id: "{{ az_spn_client_id }}"
ceres_azsetup_az_spn_secret: "{{ az_spn_secret }}"

##
## Azure Landing Zone Values
##
#
# Azure Location (will pull location from resource group)
ceres_azsetup_az_location:
#
# Virtual Network
ceres_azsetup_az_vnet_name: "ceres-01-vnet"
ceres_azsetup_az_vnet_ip_block: "192.168.68.0/22"
#
# Subnet
ceres_azsetup_az_subnet_name: "ceres-01v-01-subnet"
ceres_azsetup_az_subnet_ip: "192.168.68.0/24"
#
# Application Security Group
ceres_azsetup_az_asg_name: "ceres-awx-01-asg"
#
# Network Security Group
ceres_azsetup_az_nsg_name: "ceres-01v01s-01-nsg"
#  nsg_k3s_ip is an ip cidr that covers both k3s cluster and service cidrs
ceres_azsetup_az_nsg_k3s_ip: "10.42.0.0/15"
#  nsg_ib_asg_ip is the source ip on inbound rule to awx asg
#  set to any ip for now, should be set to owners public ip
ceres_azsetup_az_nsg_ib_asg_ip: "*"
#  nsg_ob_asg_ip is the destination ip on outbound rule from awx asg
#  set to any ip for now, should be set to automation target ips/cidrs
#  For a single ip/cidr use quoted values e.g., "10.0.0.0", "10.0.0.0/24"
#  For multiple ips/cidrs use list values e.g., ["10.0.0.0/24", "10.10.10.0/24"]
ceres_azsetup_az_nsg_ob_asg_ip: "*"


##
## Azure VM Values
##
#
# Hostname
ceres_azsetup_az_vm_hostname: "ceres-az01"
#  dnslabel is a unique name that will be generated
ceres_azsetup_az_vm_dnslabel:
#  user is the user name to be created on the vm
ceres_azsetup_az_vm_user: azureuser
#  private_key is the name of the private key file (public key will have .pub appended)
ceres_azsetup_az_vm_private_key: ssh.ceres-az.key
ceres_azsetup_az_vm_pub_key_contents:
#
# Public IP Address
ceres_azsetup_az_pubip_name: "ceres-01-public"
#  fqdn will be pulled from public ip on creation
ceres_azsetup_az_pubip_fqdn:


