---
# defaults main.yml file

## awx operator installer defaults
ceres_awx_oper_helm_repo_url: "https://ansible.github.io/awx-operator/"
ceres_awx_oper_helm_repo_name: awx-operator
ceres_awx_oper_helm_deploy_name: awx-operator
ceres_awx_oper_helm_deploy_chart_ref: awx-operator/awx-operator
ceres_awx_oper_helm_deploy_namespace: awx
ceres_awx_oper_install: True  # If set to False will uninstall awx

## k3s env
ceres_awx_kube_app_defs_path: /root/kube_app_defs
ceres_awx_ansible_token_file: /etc/rancher/k3s/ansible-node-token
ceres_awx_ansible_token:
ceres_awx_admin_pass_file: /etc/rancher/k3s/awx-admin-pass
ceres_awx_admin_pass:

## awx values
ceres_awx_value_resourcename: awx
ceres_awx_value_admin_user: admin
ceres_awx_value_servicename: awx-service
ceres_awx_value_requirements:
  postgres_resource_requirements: # Settings based on a 2 core cpu 4GB ram system - adjust as needed
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  postgres_storage_requirements:
    requests:
      storage: 2Gi
    limits:
      storage: 5Gi
  web_resource_requirements:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 750m
      memory: 1Gi
  task_resource_requirements:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  ee_resource_requirements:
    requests:
      cpu: 250m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 1Gi

## awx ingress
ceres_awx_node_fqdn:
ceres_awx_ingress_connect:
ceres_awx_ingress_install: True


