---
# defaults main.yml file

## awx operator installer defaults
ceres_awx_oper_helm_repo_url: "https://ansible.github.io/awx-operator/"
ceres_awx_oper_helm_repo_name: awx-operator
ceres_awx_oper_helm_deploy_name: awx-operator
ceres_awx_oper_helm_deploy_chart_ref: awx-operator/awx-operator
ceres_awx_oper_helm_deploy_namespace: awx

## k3s env
ceres_awx_ansible_token_file: /etc/rancher/k3s/ansible-node-token
ceres_awx_ansible_token:

## 

